Upgrade frontend to Vue 2.7
dandi/dandi-archive pull request #1258
Opened 2022-08-30 20:47 UTC by mvandenburgh

Upgrades the frontend to Vue 2.7, which includes the composition API natively. Crucially, this allows us to abandon usage of the [vue composition API plugin](https://github.com/vuejs/composition-api), which will be going EOL at the end of this year. There's also been some major bugs found in that plugin, so I think it makes sense to do this upgrade before diving into some of the console errors and reactivity bugs we've been seeing in the frontend to at least rule it out as the source.

There's other stuff we can and should do at some point, like switching to `<script setup>` syntax and using vite instead of webpack, since presumably that will ease the burden when we upgrade to Vue 3 someday. But for now, this is the bear minimum needed to move to Vue 2.7.

Closes #1189.

2022-08-31 20:46 UTC, AlmightyYakob requested changes
Looks good overall, just one main question

2022-09-01 01:13 UTC, mvandenburgh commented on web/src/components/DandisetsPage.vue
> +        search: props.search ? useRoute().query.search : null,
I think you're right, I used the existing `route` variable and it seems to work fine. At one point I was having trouble with reactivity, but it seems likely that something else was causing that.

2022-09-01 20:25 UTC, AlmightyYakob approved these changes
Looks good to me, I think #1259 can be merged into this branch. Any reason this PR is still set as draft?

2022-09-01 20:26 UTC, mvandenburgh commented
> Looks good to me, I think #1259 can be merged into this branch. Any reason this PR is still set as draft?

Just as an extra reminder not to merge this before #1259 is merged in. I'll merge #1259 into this branch now, and then merge this branch into `master` once CI is green.

2022-09-01 21:02 UTC, merged