Refactor dandiset create/delete methods
dandi/dandi-archive pull request #1292
Opened 2022-09-26 15:54 UTC by danlamanna

2022-09-26 16:59 UTC, yarikoptic commented
I would have appreciated description or pointer to "motivation" behind this PR and in particular change of "visible" API in terms of return error code (a somewhat more informative 403 Forbidden  with 400 Bad Request whenever requesting to delete dandiset which IIRC should be allowed for admins).

2022-09-26 17:11 UTC, danlamanna commented
> I would have appreciated description or pointer to "motivation" behind this PR and in particular change of "visible" API in terms of return error code (a somewhat more informative 403 Forbidden with 400 Bad Request whenever requesting to delete dandiset which IIRC should be allowed for admins).

I wanted to open the PR as a draft since it's not final or ready for feedback yet, but I also wanted to see if CI was passing (it's been incredibly flaky lately). I should have noted that in the description, but I updated the title for now. Re dandiset deletion, admins aren't allowed to delete a dandiset if it has published versions.

2022-09-27 17:15 UTC, AlmightyYakob requested changes

2022-09-28 05:02 UTC, danlamanna commented on dandiapi/api/views/dandiset.py
> +            embargo=query_serializer.validated_data['embargo'],
It shouldn't because embargo is a valid field on the serializer, it'll just return False (the default).

2022-09-28 16:15 UTC, danlamanna commented on dandiapi/api/views/dandiset.py
> +            embargo=query_serializer.validated_data['embargo'],
No, I failed at my attempt to reproduce. I did it on the serializer itself which reimplements `__getitem__`.

2022-09-28 16:33 UTC, AlmightyYakob approved these changes

2022-09-28 16:43 UTC, mvandenburgh commented on dandiapi/api/services/dandiset/__init__.py
> +    identifier: int = None,
```suggestion
    identifier: int | None = None,
```
Interesting that this doesn't fail type-checking. Pylance/pywright reports it as an error for me locally, but mypy doesn't catch it in CI....

2022-09-28 16:44 UTC, mvandenburgh commented on dandiapi/api/services/dandiset/__init__.py
> +) -> Tuple[Dandiset, Version]:
```suggestion
) -> tuple[Dandiset, Version]:
```
We can use lowercase collections types since we're on python 3.10.

2022-09-28 17:31 UTC, merged