Refactor asset create/update/delete
dandi/dandi-archive pull request #1352
Opened 2022-11-04 17:32 UTC by danlamanna

This is a general refactor of asset create/update/delete code. This PR doesn't alter any existing functionality, it just restructures the internal API.

@AlmightyYakob cc'ing you because this slightly touches asset path code

2022-11-08 16:46 UTC, AlmightyYakob requested changes
This looks great! Just a few questions/comments

2022-11-08 20:52 UTC, mvandenburgh reviewed
Same questions as Jake but otherwise this looks good to me :+1:

2022-11-09 19:25 UTC, danlamanna commented on dandiapi/api/services/asset/__init__.py
> +        asset.save()
No reason, probably just a vestige of some copy/paste.

2022-11-09 19:25 UTC, danlamanna commented on dandiapi/api/services/asset/metadata.py
> +        return
I don't disagree, but I'm just moving this function so I would rather not change behavior in this PR.

2022-11-09 19:26 UTC, danlamanna commented on dandiapi/api/services/asset/__init__.py
> +        version.assets.remove(asset)
It should, I fixed it.

2022-11-09 20:11 UTC, AlmightyYakob approved these changes

2022-11-09 22:52 UTC, merged