Add text from the Handbook to the rejected user email
dandi/dandi-archive pull request #2022
Opened 2024-09-05 14:50 UTC by kabilar

2024-09-05 15:15 UTC, waxlamp requested changes
I think the new text makes more sense _after_ the rejection reason block. Then it's "you were denied; here's why; here's some helpful info as a call to action".

2024-09-05 15:25 UTC, kabilar commented
> I think the new text makes more sense _after_ the rejection reason block. Then it's "you were denied; here's why; here's some helpful info as a call to action".

Thanks @waxlamp.  I was actually hoping that we don't use the rejection reason block often.  This would limit the amount of manual work that Yarik has to do, and provide a standard response.  The reason for denial would be that an academic email is not associated with the GitHub account.  And if an admin wanted to provide further explanation, then the rejection reason block would be available.

2024-09-05 15:31 UTC, kabilar commented
> > I think the new text makes more sense _after_ the rejection reason block. Then it's "you were denied; here's why; here's some helpful info as a call to action".
> 
> Thanks @waxlamp. I was actually hoping that we don't use the rejection reason block often. This would limit the amount of manual work that Yarik has to do, and provide a standard response. The reason for denial would be that an academic email is not associated with the GitHub account. And if an admin wanted to provide further explanation, then the rejection reason block would be available.

Agree that if we do use the rejection reason block, it makes more sense to be above the template text.  So I have moved the block.

2024-09-05 16:48 UTC, waxlamp approved these changes
I left one suggestion to soften and clarify what to do without an academic email address, but otherwise this looks good.

2024-09-05 16:48 UTC, waxlamp commented on dandiapi/api/templates/api/mail/rejected_user_message.txt
> +- Without an academic email, account approval is still possible under specific circumstances. Appeal decisions at help@dandiarchive.org.
```suggestion
- Without an academic email, account approval is still possible under specific circumstances. You can appeal the decision by contacting help@dandiarchive.org.
```

2024-09-09 18:24 UTC, yarikoptic approved these changes

2024-09-16 20:19 UTC, kabilar commented
Hi @waxlamp, would you be able to deploy these changes this week?  Thank you.

2024-09-20 00:04 UTC, merged

2024-09-20 00:04 UTC, waxlamp commented
> Hi @waxlamp, would you be able to deploy these changes this week? Thank you.

Done!