Create permissions service layer
dandi/dandi-archive pull request #2115
Opened 2024-12-18 20:19 UTC by jjnesbitt

The goal of this PR is to abstract most of the use of `django-guardian` into the permissions service layer, instead exposing functions that achieve the same effect. This has the following benefits:

1. Consolidates permission logic in the application, most notably used in endpoints.
2. Allows for easier modification or extension of our permissions logic.

One notable use case for this is forks of the codebase that may need to modify how permissions are done (e.g. LINC). This refactor and consolidation makes that much easier, as everything can be easily found in one file. cc @aaronkanzer.

2025-01-02 21:24 UTC, mvandenburgh requested changes

2025-01-02 21:24 UTC, mvandenburgh commented on dandiapi/api/views/asset.py
>          # User must be an owner on any of the dandisets this asset belongs to
The logic changed so that we're not checking the user's dandisets here to determine asset ownership, so this comment is outdated now
```suggestion
```

2025-01-02 21:24 UTC, mvandenburgh commented on dandiapi/api/services/permissions/dandiset.py
> +    ).order_by('created')
This comment is incorrect, this actually can be done with one query -
```suggestion
def get_visible_dandisets(user: AbstractBaseUser | AnonymousUser) -> QuerySet[Dandiset]:
    """
    Return a queryset containing all dandisets visible to the given user.

    This is basically all dandisets except embargoed dandisets not owned by the given user.
    """

    # Get dandisets owned by this user, potentially including embargoed dandisets
    owned_dandisets = Dandiset.objects.filter(
        pk__in=(
            DandisetUserObjectPermission.objects.filter(
                user=user, permission__codename='owner'
            ).values('pk'),
        )
    )

    open_dandisets = Dandiset.objects.filter(embargo_status=Dandiset.EmbargoStatus.OPEN)

    # The union of these two sets is the set of dandisets visible to the user
    return owned_dandisets.union(open_dandisets)
```

Although I see now that this was copied from another file and introduced in this PR, so we can also defer it to a follow up if you prefer.

2025-01-02 22:01 UTC, jjnesbitt commented on dandiapi/api/models/dandiset.py
> +        return get_dandiset_owners(self)
That sounds great to me. I didn't do that in an attempt to limit the scope of this PR, but if you think it's warranted, I'm happy to include that change.

2025-01-02 22:07 UTC, jjnesbitt commented on dandiapi/api/services/permissions/dandiset.py
> +    return removed_owners, added_owners
Good idea :+1:

2025-01-02 22:14 UTC, jjnesbitt commented on dandiapi/api/services/permissions/dandiset.py
> +    return user.has_perm('owner', dandiset)
This is mostly a typing issue. The user type that is thrown around before any checks are done on it is `AbstractBaseUser | AnonymousUser`. So if we use the type `User` instead of `AbstractBaseUser`, type errors will be thrown in all the places where we invoke this function, and we'd either have to ignore that type error, or cast the type before calling this function, which is very messy.

I figure it's easiest to accept the most generic user type possible, and centralize the filtering in this function, rather than all the places it's invoked. I originally had the user type as `User`, but ran into the typing issues I mentioned, and so went with this.

2025-01-02 22:16 UTC, jjnesbitt commented on dandiapi/api/views/asset.py
>          # User must be an owner on any of the dandisets this asset belongs to
How has the logic changed? `is_owned_asset` is called right below this line, which is what this comment is referring to.

2025-01-02 22:30 UTC, jjnesbitt commented on dandiapi/api/services/permissions/dandiset.py
> +    ).order_by('created')
It seems like implementing this causes some tests and endpoints to fail, due to the union operation preventing much else from happening to a queryset. It actually seems like that was captured in the comment:

```
    # We would like to do something like:
    # queryset = Dandiset.objects.filter(embargo_status=OPEN).union(get_objects_for_user(...))
    # but you cannot filter or perform many other common queryset operations after using
    # union().
```

Although I imagine you're referring to the first part of that comment that mentions django-guardian. If we can clean this up, I'd prefer to do it in a follow-on PR. Although I'd like to continue to stay away from `union` if we can.

2025-01-02 22:43 UTC, mvandenburgh commented on dandiapi/api/services/permissions/dandiset.py
> +    ).order_by('created')
Sounds good. I think we could avoid `union`, but we can defer further discussion to a future PR

2025-01-02 22:45 UTC, mvandenburgh commented on dandiapi/api/views/asset.py
>          # User must be an owner on any of the dandisets this asset belongs to
"Logic changed" was probably the wrong wording, I meant that we're not explicitly checking dandiset ownership in the code under this comment anymore, but instead just calling the opaque `is_owned_asset` function.

2025-01-03 16:51 UTC, jjnesbitt commented on dandiapi/api/views/asset.py
>          # User must be an owner on any of the dandisets this asset belongs to
I still think the comment is valid, as it describes both why we're calling `is_owned_asset`, as well as the fact that this check returns true if the user is an owner of _any_ dandiset this asset belongs to.

2025-01-03 19:37 UTC, mvandenburgh commented on dandiapi/api/views/asset.py
>          # User must be an owner on any of the dandisets this asset belongs to
Fair enough, I don't have any objections to keeping it

2025-01-03 19:38 UTC, mvandenburgh approved these changes

2025-01-08 18:09 UTC, merged

2025-01-21 00:12 UTC, waxlamp commented on dandiapi/api/services/permissions/dandiset.py
> +    ).order_by('created')
@jjnesbitt or @mvandenburgh, could one of you file an issue to capture this?