Display validation errors on DLP for embargoed dandisets
dandi/dandi-archive pull request #2122
Opened 2024-12-21 18:35 UTC by mvandenburgh

Fixes #2089.

We currently don't display validation errors on the DLP for embargoed dandisets. This seems to be an oversight due to much of the UI being duplicated between the `DandisetPublish` and `DandisetUnembargo` components. I've taken an initial stab at refactoring some of the duplicate templates into a reusable component in this PR, but we could probably clean it up a bit more. 

The text displayed when the Assets Summary is missing (`This Dandiset does not contain any assets.`) is also slightly misleading. A dandiset that contains _only invalid assets_ will also not have an Assets Summary; I've updated that text to reflect that.

2024-12-21 18:42 UTC, mvandenburgh commented
See https://deploy-preview-2122--gui-staging-dandiarchive-org.netlify.app/dandiset/215957 for working example

2025-01-02 18:50 UTC, jjnesbitt commented on web/src/components/DLP/OverviewTab.vue
> +              This Dandiset does not contain any valid assets.
I know this is technically the most concise way to phrase this, but I wonder if people will take both wordings to mean the same thing. They might say "hold on, I just uploaded a bunch of assets that I _know_ are valid", even though "valid" might mean different things to us vs them. Maybe we should reword it to something like:

`This dandiset does not contain any valid assets. Please check the validation errors to address any issue with asset metadata.`, or something like that :man_shrugging: .

2025-01-02 18:51 UTC, jjnesbitt requested changes
LGTM, just had one suggestion.

2025-01-02 20:22 UTC, mvandenburgh commented on web/src/components/DLP/OverviewTab.vue
> +              This Dandiset does not contain any valid assets.
I added a message about the validation errors that only appears when there are asset validation errors - https://github.com/dandi/dandi-archive/pull/2122/commits/9fcf1dd8053a0a96ec4dd2c06f980b30ce8bb01b. What do you think?

2025-01-02 22:47 UTC, jjnesbitt commented on web/src/components/DLP/OverviewTab.vue
> +              This Dandiset does not contain any valid assets.
I think the logic in that commit is inverted. This can be seen in [this](https://deploy-preview-2122--gui-staging-dandiarchive-org.netlify.app/dandiset/101233) example. It should show the extended message, but just shows the short one. While the [other](https://deploy-preview-2122--gui-staging-dandiarchive-org.netlify.app/dandiset/215957) example shows the extended message, even though it has zero assets.

2025-01-02 22:48 UTC, jjnesbitt commented on web/src/components/DLP/OverviewTab.vue
> +              This Dandiset does not contain any valid assets.
Besides that I think the extended message is perfect.

2025-01-02 23:51 UTC, mvandenburgh commented on web/src/components/DLP/OverviewTab.vue
> +              This Dandiset does not contain any valid assets.
Oh I inverted the logic to test it, and forgot to change it back :man_facepalming: . Thanks for catching that, I fixed it

2025-01-03 16:44 UTC, jjnesbitt approved these changes

2025-01-03 16:49 UTC, merged