[WIP] Redesigned Meditor
dandi/dandi-archive pull request #862
Opened 2022-01-28 21:20 UTC by mvandenburgh

2022-01-28 21:24 UTC, mvandenburgh commented
This is not done yet, I opening this just to see how this works with staging data - I still have to clean up some styling and fix some things.

2022-02-09 20:14 UTC, AlmightyYakob requested changes
A couple of suggestions, but otherwise looks good! Great job with this

2022-02-10 18:49 UTC, mvandenburgh commented on web/src/components/Meditor.vue
> +                :editor-interface="editorInterface"
Sounds good to me, I'll implement this.

2022-02-14 22:59 UTC, mvandenburgh commented on web/src/components/VJsfWrapper.vue
> +          <span class="mr-1">Save Item</span>
Done https://github.com/dandi/dandi-archive/pull/862/commits/f3c38a00b4aff20b6628bc45857624df86aa4b5d

2022-02-14 23:01 UTC, mvandenburgh commented on web/src/components/Meditor.vue
> +                :editor-interface="editorInterface"
Punting this to a future PR as we discussed offline. Issue https://github.com/dandi/dandi-archive/issues/894

2022-02-15 00:10 UTC, AlmightyYakob approved these changes

2022-02-15 00:11 UTC, merged